### ISSUE TITLE
affix taller than relative element

### ISSUE THREAD

**Issue by rmartins90** [eddiemf/vue-affix#1]
Does this lib supports case when sidebar is taller than  relative element?

**Comment by eddiemf** [comment]
What do you mean by being taller than the sidebar? The relative element in the <a href="https://eddiemf.github.io/vue-affix/examples/example-1.html" target="_blank">demo</a> is taller than the sidebar. 

Could you give me a fiddle so I can see? I still didn't have the time to test it in a project so it probably might have some bugs.

Thanks!

**Comment by rmartins90** [comment]
I updated both title and content of this issue. It's the inverse of demo

**Comment by eddiemf** [comment]
Oh I see, indeed it is buggy when the sidebar is taller, I'll have a look at it tonight, thanks for the feedback :)

**Comment by eddiemf** [comment]
I'm not really sure what the default behavior should be in the case the Affix is taller than the relative element, so I simply don't apply the affix in that case and the sidebar stays static. I've tested with bootstrap's affix and it moves the affixed element up in a glitchy way when that happens, so I preferred to just ignore and don't apply the affix.

8e874e7fd8bd20a09e188922bba2aab032a02a4c Fixed

**Comment by rmartins90** [comment]
Think that's exactly the correct way to behave ;) Will you launch a new version to npm?

**Comment by eddiemf** [comment]
Already launched v0.1.5 :)
