### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by orlyyani** [eddiemf/vue-affix#12]
Does this contain any animation?

**Comment by eddiemf** [comment]
What kind of animation do you need? I can't see how it could animate since it only makes an element fixed after a threshold. Do you have any examples I can see?

**Comment by orlyyani** [comment]
Just like what you have in your demo, a smooth scroll. it would be better if you add some.

**Comment by eddiemf** [comment]
Ohh, you mean the animation when clicking to scroll? That is done with other plugin also developed by me, it's called `vue-scrollactive` (https://github.com/eddiemf/vue-scrollactive). You can customize the scroll animation and track the current active section just like in the demo.

`vue-affix` should only help you to affix an element based on another relative element, not deal with scrolling and the menu at all.

**Comment by orlyyani** [comment]
I see, well thanks!
