### ISSUE TITLE
Validate the offset object

### ISSUE THREAD

**Issue by robbeman** [eddiemf/vue-affix#16]
Small suggestion: add validation to the offset object. I added `:offset="{top: 20, right: 20}"` which obviously didn't work. (I was trying out some other similar plugins and this lingered from one of those, so my bad.)

But I spent some time looking for the reason why it didn't work. By adding a validation method to the offset prop it could save people some time.

Otherwise, things seem to work fine. Thanks for this nice plugin.

**Comment by eddiemf** [comment]
Cool, I'll look into it, thanks for the suggestion :D
