### ISSUE TITLE
Disable affix behaviour based on css media queries

### ISSUE THREAD

**Issue by rmartins90** [eddiemf/vue-affix#2]
It's possible to disable affix behaviour for specific CSS media queries?

**Comment by eddiemf** [comment]
That's something I had already addressed to be done. I will add a prop where it will enable/disable the plugin based on its value, so you can pass a function and do the media queries via JS and return true/false whenever you want it to be enabled/disabled.

I'll try to do it not later than tonight, maybe sooner :)

**Comment by eddiemf** [comment]
Done. I'll update the docs tonight, but you can use it already passing a boolean to the prop `enabled`:

`<affix :enabled="yourFunction()"></affix>`

:)

**Comment by rmartins90** [comment]
You're the best! :D v0.1.6?

**Comment by eddiemf** [comment]
Thanks :D 
Yeah, v0.1.6 is live already.
