### ISSUE TITLE
Dynamic width

### ISSUE THREAD

**Issue by NicTorgersen** [eddiemf/vue-affix#20]
I am using this with a heading, so it will follow the current context when scrolling through a bunch of elements with inputs (so it's easy to know what field means what without having to annotate each one).

My problem is that people use different viewport widths. The element can not have a fixed width. Why can I not have this component copy the start width and just keep that?

Other than that, thanks for your awesome work.

**Comment by NicTorgersen** [comment]
nvm im dumb

**Comment by Entrio** [comment]
How did you solve this?

**Comment by NicTorgersen** [comment]
This was a while ago. I revisited some of that code now, and I believe all I did was define a data-object with a width-parameter. On my created-hook I grabbed the current width of the containing element and used that (with a helper-function, `getElementWidth`).

Then I added some event listeners and destruction to mounted and beforeDestroy.

Data
```js
data() {
  return {
    heading: {
      width: '0px',
    }
  }
}
```
Hooks
```js
created() {
  this.heading.width = this.getElementWidth('element-id', 'px')`
},
```
```js
beforeDestroy() {
  window.removeEventListener('resize', this.handleWindowResize) // quite important to remove the event listener.
},
```
```js
mounted() {
  window.addEventListener('resize', this.handleWindowResize)
},
```
Methods
```js
methods: {
  getElementWidth(id, units) {
    return document.getElementById(id).offsetWidth + units
  },

  handleWindowResize() {
    this.heading.width = this.getElementWidth('element-id', 'px')
  },
}
```

My markup was then something like

```html
<affix <!-- other settings -->
       :style="{width: heading.width}">
<!-- stuff -->
</affix>
```
This can probably be improved drastically.

Hope this helped.

**Comment by Entrio** [comment]
I tried that method and it wasnt doing what i needed. I ended up solving it the following way:
Note the ref tag on the div

```
<div ref="userinfo" class="margin-top-1">
            <affix class="sidebar-menu">...</affix>
</div>
```

And the methods

```
created() {
            window.addEventListener('resize', this.handleWindowResize);
        },

        mounted() {
            this.heading.width = this.$refs.userinfo.clientWidth + 'px';
        },

        beforeDestroy() {
            window.removeEventListener('resize', this.handleWindowResize) // quite important to remove the event listener.
        },

        methods: {
            getElementWidth(id, units) {

                return document.getElementById(id).offsetWidth + units
            },

            handleWindowResize() {
                this.heading.width = this.$refs.userinfo.clientWidth + 'px';
            },
        }
```


Thanks for the help!

**Comment by klivak** [comment]
@Entrio, many thanks!
