### ISSUE TITLE
It's possible pass $this.refs.elem instead selector?

### ISSUE THREAD

**Issue by gtso86** [eddiemf/vue-affix#22]
Instead to use selector to pass `relative-element-selector` it's possible use $ref?

**Comment by eddiemf** [comment]
No, but you can always get the ID of the element using the `$ref` and pass this ID :)

**Comment by Danon** [comment]
ID is not guaranteed to be unique in HTML document, is it? I also like my elements specified explicitly, thank through name/id/class/selector etc.
