### ISSUE TITLE
Ability to use a scroll container other than window

### ISSUE THREAD

**Issue by chriseverson** [eddiemf/vue-affix#23]
Currently vue-affix only supports scroll events that take place on the window object. Ideally this could also be applied to other DOM objects when the window isn't the main scrollable container.

A common use case for this functionality would be when implementing something like [Slideout.js](https://slideout.js.org/) which disables scrolling on the window, instead replacing it with an interior DOM element.

**Comment by eddiemf** [comment]
Thanks for the help :)
