### ISSUE TITLE
Facebook like affix

### ISSUE THREAD

**Issue by rmartins90** [eddiemf/vue-affix#3]
I'm trying to achieve something that I don't believe it's possible to do using this lib. But I want to hear what are your thoughts on this. I want to do affix like Facebook - this means that if sidebar is taller than viewport it'll scroll until the end of that element.

**Comment by eddiemf** [comment]
Humm, I see. That's not possible indeed, I'll have a look tonight and see if I can find a way to implement this behavior. Probably yes :)

**Comment by eddiemf** [comment]
Sorry for the waiting, it took longer than I thought, 2 sleepless nights to be precise xD
Could you make some tests in your environment with the new feature? Just add the prop `:scroll-affix` to your component and set it to true when you want the "facebook like" affixing.

**Comment by rmartins90** [comment]
Just did a quick test and it seems that's working very good. I'm wondering if it behaves good with dynamic content on both affix and relative element.

**Comment by eddiemf** [comment]
That's great :D 
I did some testings adding dynamic content directly in the browser and it looked alright, but maybe in a big project something might show up, keep me updated if you find anything :)
