### ISSUE TITLE
incorrect top position when loading page scrolled halfway down

### ISSUE THREAD

**Issue by 719media** [eddiemf/vue-affix#36]
If you refresh the demo page while being scrolled "halfway" down, then scroll to top, the top position is incorrect.

https://eddiemf.github.io/vue-affix-demo/

![Screen Shot 2019-03-18 at 2 14 45 PM](https://user-images.githubusercontent.com/5942229/54564137-43008c00-4988-11e9-848f-0f436679d7e2.png)

using chrome 73 on mac

**Comment by 719media** [comment]
Sorry, perhaps this should be filed under the repo `eddiemf/vue-affix-demo` and mentioned to at least update the vue-affix version there

**Comment by eddiemf** [comment]
Thanks for the info, I'll take a look at it this weekend :)
