### ISSUE TITLE
vue affix bugs in latest version when affixed element has scroll (height larger than viewport)

### ISSUE THREAD

**Issue by 719media** [eddiemf/vue-affix#37]
I've  cobbled together a copy of the vue-affix-demo example with latest vue and vue-affix 0.5.0 to replicate the problem:

https://jsfiddle.net/rsdan1kz/

if you just scroll to the bottom, you'll see how the affix portion will flicker back and forth with each scroll element firing.

There is another problem as well. If you scroll down partway, then begin to scroll up, the affixed element "jumps" back to position 0.

**Comment by dylanmcgowan** [comment]
I am also experiencing the explained "flickering" and "jumping" when adding the `scrollAffix` prop to the `<affix />` component!

**Comment by eddiemf** [comment]
Oh boy that sounds bad, I'll take a look at it this weekend and release a fix ASAP :)

Thanks for the help!

**Comment by Dronax** [comment]
Yep. This bug and I see. Please fix it. Thanks)

**Comment by eddiemf** [comment]
Sorry for the delay guys, only now I could do something about it. I've released an update, can you please confirm if the new version is working properly? :)

**Comment by Dronax** [comment]
Yep. Working very well. Thanks @eddiemf :)
