### ISSUE TITLE
Broken for relativeElement with dynamic height

### ISSUE THREAD

**Issue by mbajur** [eddiemf/vue-affix#4]
Hello!

I've been trying to use this plugin for my list of ajax-fetched results and it seems vue-affix can't properly deal with the relativeElement which height is changing during his lifetime. vue-affix saves the dimensions of relativeElement when it's mounted. If it's height changes, vue-affix is not catching the change.

I tried to extract the initialization logic to separate methods to make it able to control the flow but i'm not too good at JS and it's still broken, just in a different way. I'm gonna try to show you some demo of this later but, for now: is there anything you can say is 100% wrong in my code?: https://gist.github.com/mbajur/8273745f03846fd153e0f4b3083be9f3

Sample usage:

```
<template>
  <affix :delayed="true" ref="affix">...</affix>
</template>

<script>
  export default {
    // ...

    methods: {
  
      // First fetch
      onAjaxFetched () {
        this.$refs.affix.start()
      },

      // All the next fetches
      onAjaxFetchedMore () {
        this.$refs.affix.update()
      }
    }

    // ...
  }
</script>
```

Thanks in advance!

**Comment by mbajur** [comment]
Ok, i created a sample project to illustrate my problem: https://github.com/mbajur/vue-affix-delayed

![image](https://user-images.githubusercontent.com/581569/28409160-0946f250-6d3a-11e7-852a-e344971b8c7e.png)

Here are few scenarios i have a problem with:

1. First of all - the original package. You can test the behaviour i mentioned in original post by uncommenting the regular vue-affix import in `App.vue` and commenting the custom one. Loading first set of results is delayed so vue-affix makes it's calculations for non-filled results div (which has no height). When results comes up - affix thinks bottom of a relative div is way higher than it really is. You can see it by just scrolling down the page and looking at the green element.
2. For the first, initial set of results, red affix is not working at all. After adding another set of 10 results, it starts to work but acts weird (start scrolling down - red box will start to scroll with the page way too early)
3. Load the page, scroll to the bottom and refresh the page. This is where things goes mad - the red box has a weird top offset instead of `top: 0` and is basically permanently sticked to the top. Untill you click the "Add 10 results" - this is fixing the issue.

**Comment by eddiemf** [comment]
I'm still working really hard on #3 and will probably finish it tonight, then I'll have a look at this closely. I was sure it would have problems with dynamic content but didn't have the time to test yet, sorry for the lack of time :(

Thanks for the feedback!

**Comment by mbajur** [comment]
Hey, sure, don't stress yourself, i really appreciate what you've done so far in here :) That's also probably the only affix/sticky plugin for vue out there and i need to use affix/sticky in my project pretty bad so i'm gonna do whatever i can to help in here with that. Let me know if you need any more feedback or testing when time will come.

**Comment by eddiemf** [comment]
Thanks for that :D 

I'm changing a lot of things while implementing #3, refactoring a lot of code, I made this plugin in one day last weekend and it still have a lot of early stage code, but when I finish it I will sure ask for more tests regarding this issue :)

**Comment by eddiemf** [comment]
Hello, could you update the lib and test it again? I rewrote almost the whole code and I wanted to see if your problem still persists. I didn't work to fix it but it might be good after this refactoring. If you still have problems, describe them here again and I'll take a close look this weekend.

Thanks :)

**Comment by mbajur** [comment]
Ha! yes, now it all works as it should. All my issues are gone :) Thanks for the awesome work!

**Comment by eddiemf** [comment]
Awesome :D 

Its good to know the performance is better, as I said, i rewrote almost everything and it's much better now, I just need to update the docs with the new functionalities.
