### ISSUE TITLE
Affix scrolling offset not working

### ISSUE THREAD

**Issue by arpitprod** [eddiemf/vue-affix#5]
When I write offset like  :offset="{top: 50}" in affix then affix stopped working and moving above with scrolling

**Comment by eddiemf** [comment]
Hello, you can't actually set only one option for offset as I see now, I'll add it in a next update, for now just set the bottom property to 40 as it is the default value and it should work without problems :)

Thanks for the feedback!

**Comment by arpitprod** [comment]
thanks, it's working now
