### ISSUE TITLE
Doesn't work in IE11?

### ISSUE THREAD

**Issue by dosstx** [eddiemf/vue-affix#7]
Works fine in Chrome and Firefox, but does not work with IE11. Also, your demo in IE11 has the same issue of not affixing to the viewport in IE11. Can anyone replicate?

**Comment by eddiemf** [comment]
I'll have a look at it, probably just need a polyfill for something since I didn't actually test it. Thanks for catching that!

**Comment by dosstx** [comment]
No problem. I don't know if it's a polyfill issue because I have it already . Also, I noticed it doesn't work in mobile devices (safari and I think Chrome for iPad).

**Comment by dosstx** [comment]
Not sure if this helps, but look into how Bootstrap handles affix because it works great in all browsers. Also, it appears that IE10+ does not support the CSS rule `position: sticky` .

**Comment by eddiemf** [comment]
Yeah I'll take a look this weekend :)
I don't actually use `position: sticky` for this plugin, biggest reason is for compatibility hehe, problem is I don't have easy access to Windows for testing, but this weekend I'll provide and test it :D

**Comment by eddiemf** [comment]
Hello, can you update the plugin and test it again on IE? 

I've made some tests and it looks like it's working on IE10+ now.
