### ISSUE TITLE
suggetion to disable the component in mobile

### ISSUE THREAD

**Issue by moyvera** [eddiemf/vue-affix#8]
Hello there !! 

I'm newbie at Vuejs and your component is being very useful for my project. I saw the prop disabled which I'm using to disable the component but...

What do you think is the best way to use it in case the webapp is on mobile ?

**Comment by eddiemf** [comment]
Hello, I'm glad to hear it's helping you!

You can just have a variable in your component that will be true/false depending on a verification and always pass this variable as a prop to vue-affix. You can either check the browser viewport width and assign false if it's lower than 1024 for example, or you can check the header to see the UserAgent that was sent.That will depend on your application needs. 

You can find some pre made verifications based on UserAgent on google, while for the width verification you can just `if (window.innerWidth < 1024) enabled = false`

**Comment by Culttm** [comment]
@eddiemf But in this case there is a trouble with resizing. After initializing the component calculates a wrong position with offset.

**Comment by eddiemf** [comment]
Maybe you should re-render it after resizing so it can be mounted again, preferably with a debouncing function. Let me know if that helps, or maybe post a fiddle with the bug so I can dig in and see if anything is wrong.

**Comment by makmalf** [comment]
Try using [vue-media-queries](https://github.com/flatanimals/vue-media-queries)
